#!/bin/bash

set -e

cd "$(dirname "$0")/../builtinFonts"

echo "// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh"
echo "#pragma once"
echo ""

echo "#define BOOKERLY_18_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./bookerly_18_regular.h",
  "./bookerly_18_bold.h",
  "./bookerly_18_bolditalic.h",
  "./bookerly_18_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define BOOKERLY_21_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./bookerly_21_regular.h",
  "./bookerly_21_bold.h",
  "./bookerly_21_bolditalic.h",
  "./bookerly_21_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define BOOKERLY_23_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./bookerly_23_regular.h",
  "./bookerly_23_bold.h",
  "./bookerly_23_bolditalic.h",
  "./bookerly_23_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define UNIFONT_18_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./unifont_18_regular.h",
  "./unifont_18_bold.h",
  "./unifont_18_bolditalic.h",
  "./unifont_18_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define UNIFONT_20_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./unifont_20_regular.h",
  "./unifont_20_bold.h",
  "./unifont_20_bolditalic.h",
  "./unifont_20_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define UI_10_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./unifont_10_regular.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define UI_12_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./unifont_12_regular.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define SMALL_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./unifont_8_regular.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"
