#!/bin/bash

set -e

cd "$(dirname "$0")/../builtinFonts"

echo "// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh"
echo "#pragma once"
echo ""

echo "#define BOOKERLY_12_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./bookerly_12_regular.h",
  "./bookerly_12_bold.h",
  "./bookerly_12_bolditalic.h",
  "./bookerly_12_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define BOOKERLY_14_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./bookerly_14_regular.h",
  "./bookerly_14_bold.h",
  "./bookerly_14_bolditalic.h",
  "./bookerly_14_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define BOOKERLY_16_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./bookerly_16_regular.h",
  "./bookerly_16_bold.h",
  "./bookerly_16_bolditalic.h",
  "./bookerly_16_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define BOOKERLY_18_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./bookerly_18_regular.h",
  "./bookerly_18_bold.h",
  "./bookerly_18_bolditalic.h",
  "./bookerly_18_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define GEORGIA_12_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./georgia_12_regular.h",
  "./georgia_12_bold.h",
  "./georgia_12_bolditalic.h",
  "./georgia_12_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define GEORGIA_14_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./georgia_14_regular.h",
  "./georgia_14_bold.h",
  "./georgia_14_bolditalic.h",
  "./georgia_14_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define GEORGIA_16_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./georgia_16_regular.h",
  "./georgia_16_bold.h",
  "./georgia_16_bolditalic.h",
  "./georgia_16_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define GEORGIA_18_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./georgia_18_regular.h",
  "./georgia_18_bold.h",
  "./georgia_18_bolditalic.h",
  "./georgia_18_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define UNIFONT_14_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./unifont_14_regular.h",
  "./unifont_14_bold.h",
  "./unifont_14_bolditalic.h",
  "./unifont_14_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define UNIFONT_16_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./unifont_16_regular.h",
  "./unifont_16_bold.h",
  "./unifont_16_bolditalic.h",
  "./unifont_16_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define UNIFONT_18_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./unifont_18_regular.h",
  "./unifont_18_bold.h",
  "./unifont_18_bolditalic.h",
  "./unifont_18_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define UNIFONT_20_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./unifont_20_regular.h",
  "./unifont_20_bold.h",
  "./unifont_20_bolditalic.h",
  "./unifont_20_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define UNIFONT_22_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./unifont_22_regular.h",
  "./unifont_22_bold.h",
  "./unifont_22_bolditalic.h",
  "./unifont_22_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define UNIFONT_24_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./unifont_24_regular.h",
  "./unifont_24_bold.h",
  "./unifont_24_bolditalic.h",
  "./unifont_24_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define UI_10_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./unifont_10_regular.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define UI_12_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./unifont_12_regular.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define SMALL_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./unifont_8_regular.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"
