#pragma once

#include <builtinFonts/bookerly_18_bold.h>
#include <builtinFonts/bookerly_18_bolditalic.h>
#include <builtinFonts/bookerly_18_italic.h>
#include <builtinFonts/bookerly_18_regular.h>
#include <builtinFonts/bookerly_16_bold.h>
#include <builtinFonts/bookerly_16_bolditalic.h>
#include <builtinFonts/bookerly_16_italic.h>
#include <builtinFonts/bookerly_16_regular.h>
#include <builtinFonts/bookerly_14_bold.h>
#include <builtinFonts/bookerly_14_bolditalic.h>
#include <builtinFonts/bookerly_14_italic.h>
#include <builtinFonts/bookerly_14_regular.h>
#include <builtinFonts/bookerly_21_bold.h>
#include <builtinFonts/bookerly_21_bolditalic.h>
#include <builtinFonts/bookerly_21_italic.h>
#include <builtinFonts/bookerly_21_regular.h>
#include <builtinFonts/bookerly_23_bold.h>
#include <builtinFonts/bookerly_23_bolditalic.h>
#include <builtinFonts/bookerly_23_italic.h>
#include <builtinFonts/bookerly_23_regular.h>
#include <builtinFonts/bookerly_22_bold.h>
#include <builtinFonts/bookerly_22_bolditalic.h>
#include <builtinFonts/bookerly_22_italic.h>
#include <builtinFonts/bookerly_22_regular.h>
#include <builtinFonts/bookerly_20_bold.h>
#include <builtinFonts/bookerly_20_bolditalic.h>
#include <builtinFonts/bookerly_20_italic.h>
#include <builtinFonts/bookerly_20_regular.h>
#include <builtinFonts/ebgaramond_16_bold.h>
#include <builtinFonts/ebgaramond_16_bolditalic.h>
#include <builtinFonts/ebgaramond_16_italic.h>
#include <builtinFonts/ebgaramond_16_regular.h>
#include <builtinFonts/ebgaramond_20_bold.h>
#include <builtinFonts/ebgaramond_20_bolditalic.h>
#include <builtinFonts/ebgaramond_20_italic.h>
#include <builtinFonts/ebgaramond_20_regular.h>

#include <builtinFonts/atkinson_ui_small_regular.h>
#include <builtinFonts/atkinson_ui_10_regular.h>
#include <builtinFonts/atkinson_ui_12_regular.h>
