#pragma once

#include <builtinFonts/bookerly_18_bold.h>
#include <builtinFonts/bookerly_18_bolditalic.h>
#include <builtinFonts/bookerly_18_italic.h>
#include <builtinFonts/bookerly_18_regular.h>
#include <builtinFonts/bookerly_21_bold.h>
#include <builtinFonts/bookerly_21_bolditalic.h>
#include <builtinFonts/bookerly_21_italic.h>
#include <builtinFonts/bookerly_21_regular.h>
#include <builtinFonts/bookerly_23_bold.h>
#include <builtinFonts/bookerly_23_bolditalic.h>
#include <builtinFonts/bookerly_23_italic.h>
#include <builtinFonts/bookerly_23_regular.h>
#include <builtinFonts/unifont_12_regular.h>
#include <builtinFonts/unifont_10_regular.h>
#include <builtinFonts/unifont_18_bold.h>
#include <builtinFonts/unifont_18_bolditalic.h>
#include <builtinFonts/unifont_18_italic.h>
#include <builtinFonts/unifont_18_regular.h>
#include <builtinFonts/unifont_20_bold.h>
#include <builtinFonts/unifont_20_bolditalic.h>
#include <builtinFonts/unifont_20_italic.h>
#include <builtinFonts/unifont_20_regular.h>
#include <builtinFonts/unifont_8_regular.h>
