// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

#define BOOKERLY_18_FONT_ID (1689480416)
#define BOOKERLY_21_FONT_ID (-1945616026)
#define BOOKERLY_23_FONT_ID (-1108000821)
#define UNIFONT_18_FONT_ID (1992892481)
#define UNIFONT_20_FONT_ID (-27055974)
#define UI_10_FONT_ID (1472576193)
#define UI_12_FONT_ID (-188393533)
#define SMALL_FONT_ID (1099295527)
